config/routes.rb
Rails.application.routes.draw do
  devise_for :ms_users
  resources :ms_members
  resources :ms_books
  resources :tr_loans
  resources :ms_publishers
  get "loan", to: "home#index"
  get "loan/:id", to: "home#show"
  post "loan", to: "home#create"
  get "report", to: "tr_loans#report"
  root "tr_loans#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ms_book.rb
class MsBook < ApplicationRecord
end

app/models/ms_member.rb
class MsMember < ApplicationRecord
end

app/models/ms_publisher.rb
class MsPublisher < ApplicationRecord
end

app/models/ms_user.rb
class MsUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tr_loan.rb
class TrLoan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_ms_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_ms_user!,:verify_authenticity_token
	def index
		@tr_loans_borrow = TrLoan.all

		render json:{
			values: @tr_loans,
			message: "Success!",
		}, status: 200
	end

	def show
		@tr_loans = TrLoan.find_by_id(params[:id])
		if @tr_loans.present?
			render json: {
				values: @tr_loans,
				message: "Success!",
			}, status: 200
		else
			render json: {
				values: "",
				message: "We Can't found any data!",
			}, status: 400
		end
	end

	def create
		member = MsMember.find_by_id(params[:member_id])
		book_id = params[:ms_book_id]
		status = params[:status]
		today_date = params[:borrow_date]
		if status == 'Borrow'
		@tr_loan = TrLoan.new(
			:member_name => member.name,
			:member_phone => member.phone,
			:member_email => member.email,
			:ms_book_id => 	book_id,
			:status => status,
			:borrow_date => today_date
			)

		if @tr_loan.save
			 ActionCable.server.broadcast 'loan',
              tr_loan: @tr_loan
			render json:{
				values: @tr_loan,
				message: "Success!",
			}, status: 200
		else
			render json:{
				values: "",
				message: "Failed!",
			}, status: 400
		end
		elsif status == 'Return'
			@tr_loan = TrLoan.find_by ms_book_id: params[:ms_book_id], status: 'Borrow'
			borrow_date = @tr_loan.borrow_date
			borrow_dates = borrow_date.to_date
			today_dates = today_date.to_date
			duration = @tr_loan.duration.to_i
			gap = (today_dates - borrow_dates).to_i
			gap_c = gap - duration
			if gap > duration
				bill = gap_c * 1000
			elsif gap <= duration
				bill = 0
			end	
			@tr_loan.update(
				:member_name => member.name,
				:member_phone => member.phone,
				:member_email => member.email,
				:ms_book_id => 	book_id,
				:status => status,
				:duration => duration,
				:bill => bill,
				:borrow_date => borrow_date,
				:return_date => today_date)
			ActionCable.server.broadcast 'loan',
              tr_loan: @tr_loan
			render json:{
				values: @tr_loan,
				message: "Success!",
			}, status: 200
			end
	end

	private
	def loan_params
		params.permit(:member_name,:member_phone,:member_email,:ms_book_id)
	end
end

app/controllers/ms_books_controller.rb
class MsBooksController < ApplicationController
  def index
      @ms_books = MsBook.where(is_active: true) 
  end

   def show
    @ms_book = MsBook.find(params[:id])
  end

  def new
    @ms_book = MsBook.new
  end

  def create
    @ms_book = MsBook.new(ms_books_params)

    if @ms_book.save
      redirect_to ms_books_path, notice: "Data Successfuly Created"
    else
      render 'new'
    end

  end

  def edit
    @ms_books = MsBook.find(params[:id])
  end

  def update
    @ms_books = MsBook.find(params[:id])

    if @ms_books.update(ms_books_params)
      redirect_to ms_books_path, notice: "Data Successfuly Edited"
    else
      render 'edit'
    end

  end

  def destroy
    @ms_books = MsBook.find(params[:id])
    @ms_books.update_attributes(:is_active => false)
    redirect_to ms_books_path, notice: "Data Successfuly Deleted"
  end

  

  private
  def ms_books_params
    params.require(:ms_book).permit(:id, :name, :ms_publisher_id)
  end
end

app/controllers/ms_members_controller.rb
class MsMembersController < ApplicationController
 

  def index
      @ms_members = MsMember.where(is_active: true) 
  end

   def show
    @ms_member = MsMember.find(params[:id])
  end

  def new
    @ms_member = MsMember.new
  end

  def create
    @ms_members = MsMember.new(ms_members_params)

    if @ms_members.save
      redirect_to ms_members_path, notice: "Data Successfuly Created"
    else
      render 'new'
    end

  end

  def edit
    @ms_members = MsMember.find(params[:id])
  end

  def update
    @ms_members = MsMember.find(params[:id])

    if @ms_members.update(ms_members_params)
      redirect_to ms_members_path, notice: "Data Successfuly Edited"
    else
      render 'edit'
    end

  end

  def destroy
    @ms_members = MsMember.find(params[:id])
    @ms_members.update_attributes(:is_active => false)
    redirect_to ms_members_path, notice: "Data Successfuly Deleted"
  end

  

  private
  def ms_members_params
    params.require(:ms_member).permit(:id, :name, :age, :address, :phone, :email)
  end
end

app/controllers/ms_publishers_controller.rb
class MsPublishersController < ApplicationController
  def index
      @ms_publishers = MsPublisher.where(is_active: true) 
  end

   def show
    @ms_publishers = MsPublisher.find(params[:id])
  end

  def new
    @ms_publishers = MsPublisher.new
  end

  def create
    @ms_publishers = MsPublisher.new(ms_publishers_params)

    if @ms_publishers.save
      redirect_to ms_publishers_path, notice: "Data Successfuly Created"
    else
      render 'new'
    end

  end

  def edit
    @ms_publishers = MsPublisher.find(params[:id])
  end

  def update
    @ms_publishers = MsPublisher.find(params[:id])

    if @ms_publishers.update(ms_publishers_params)
      redirect_to ms_publishers_path, notice: "Data Successfuly Edited"
    else
      render 'edit'
    end

  end

  def destroy
    @ms_publishers = MsPublisher.find(params[:id])
    @ms_publishers.update_attributes(:is_active => false)
    redirect_to ms_publishers_path, notice: "Data Successfuly Deleted"
  end

  

  private
  def ms_publishers_params
    params.require(:ms_publisher).permit(:id, :name, :age, :address, :phone, :email)
  end
end

app/controllers/tr_loans_controller.rb
class TrLoansController < ApplicationController
  skip_before_action :verify_authenticity_token, only:[:update]
  def index
      @tr_loans_borrow = TrLoan.last(1)
      @tr_loans_return = TrLoan.where.not(:return_date => nil).last(1)
      @tr_loans_form = TrLoan.new
  end

   def show
    @tr_loan = TrLoan.find(params[:id])
  end

  def new
    @tr_loan = TrLoan.new
  end

  def create
    @tr_loans = TrLoan.new(tr_loans_params)

    if @tr_loans.save
      redirect_to tr_loans_path, notice: "Data Successfuly Created"
    else
      render 'new'
    end

  end

  def edit
    @tr_loans = TrLoan.find(params[:id])
  end

  def update
    tr_loans = TrLoan.where(:id => params[:id])
    tr_loans.update(tr_loans_params)
    if tr_loans
      redirect_to tr_loans_path, notice: "Data Successfuly Edited"
    else
      render 'edit'
    end

  end
  def report
    @tr_loans = TrLoan.all
  end

  def destroy
    @tr_loans = TrLoan.find(params[:id])
    @tr_loans.update_attributes(:is_active => false)
    redirect_to tr_loans_path, notice: "Data Successfuly Deleted"
  end

  

  private
  def tr_loans_params
    params.require(:tr_loan).permit(:id, :member_name, :member_phone, :member_email, :ms_book_id, :status, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ms_books_helper.rb
module MsBooksHelper
end

app/helpers/ms_members_helper.rb
module MsMembersHelper
end

app/helpers/ms_publishers_helper.rb
module MsPublishersHelper
end

app/helpers/tr_loans_helper.rb
module TrLoansHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">
      <span>App Library</span>
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="/ms_members">Member</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ms_books">Book</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/tr_loans">Loan <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/ms_publishers">Publisher</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/report">Report</a>
      </li>
    </ul>
  </div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
            <%= current_ms_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to('Logout', destroy_ms_user_session_path, method: :delete, class: 'dropdown-item') %> 
            </div>
          </li>
        </ul>
</nav>

    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
   <% if ms_user_signed_in? %>
 <%= render 'layouts/navbar'%>
 <% end %>
<body>
    <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>

app/views/ms_books/destroy.html.erb
<h1>MsBooks#destroy</h1>
<p>Find me in app/views/ms_books/destroy.html.erb</p>

app/views/ms_books/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_books) do |ms_book| %>


        <div class="form-group">
          <%= ms_book.label :Name %>
          <%= ms_book.text_field :name, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_book.label :PublisherId %>
          <%= ms_book.text_field :ms_publisher_id, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>


        <%= ms_book.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/ms_books/index.html.erb
<div style="float: right">
 <%= link_to 'Add Data', new_ms_book_path, class: 'btn btn-success' %>
 </div>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Publisher ID</th>
      <th scope="col" width="300px">Action</th>
    </tr>
  </thead>
<% @ms_books.each do |ms_book|%>
<tbody>
<tr>
      <th scope="row"><%= ms_book.id%></th>
      <td> <%= ms_book.name %> </td>
      <td> <%= ms_book.ms_publisher_id %> </td>
     <td class="text-center">
     		<%= link_to 'Delete',ms_book_path(ms_book), method: :delete, data: {confirm: 'Delete Data ? '}, class: 'btn btn-danger' %>
              <%= link_to 'Detail', ms_book_path(ms_book), class: 'btn btn-light' %>
              <%= link_to 'Edit', edit_ms_book_path(ms_book), class: 'btn btn-primary' %>
              
            </td>
      <% end %>
</tbody>
</tr>

app/views/ms_books/new.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_book) do |ms_book| %>


        <div class="form-group">
          <%= ms_book.label :Name %>
          <%= ms_book.text_field :name, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_book.label :PublisherId %>
          <%= ms_book.text_field :ms_publisher_id, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>


        <%= ms_book.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>
</

app/views/ms_books/show.html.erb
<div class="container-fluid">
 <div class="row">
    <%= form_for(@ms_book) do |ms_book| %>


        <div class="form-group">
          <%= ms_book.label :Name %>
          <%= ms_book.text_field :name, class:'form-control', type: 'text', placeholder: '', disabled: true %>
        </div>

        <div class="form-group">
          <%= ms_book.label :PublisherId %>
          <%= ms_book.text_field :ms_publisher_id, class:'form-control', type: 'number', placeholder: '', disabled: true %>
        </div>


       <%= link_to 'Back', '/ms_books', class: 'btn btn-light' %>

    <% end %>
  </div>
</div>

app/views/ms_books/update.html.erb
<h1>MsBooks#update</h1>
<p>Find me in app/views/ms_books/update.html.erb</p>

app/views/ms_members/destroy.html.erb
<h1>MsMembers#destroy</h1>
<p>Find me in app/views/ms_members/destroy.html.erb</p>

app/views/ms_members/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_members) do |ms_member| %>


        <div class="form-group">
          <%= ms_member.label :name %>
          <%= ms_member.text_field :name, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :Age %>
          <%= ms_member.text_field :age, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :address %>
          <%= ms_member.text_field :address, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :phone %>
          <%= ms_member.text_field :phone, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :email %>
          <%= ms_member.text_field :email, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <%= ms_member.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/ms_members/index.html.erb
<div style="float: right">
 <%= link_to 'Add Data', new_ms_member_path, class: 'btn btn-success' %>
 </div>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Age</th>
      <th scope="col">Address</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col" width="auto">Action</th>
    </tr>
  </thead>
<% @ms_members.each do |ms_member|%>
<tbody>
<tr>
      <th scope="row"><%= ms_member.id%></th>
      <td> <%= ms_member.name %> </td>
      <td> <%= ms_member.age %> </td>
      <td> <%= ms_member.address %> </td>
      <td> <%= ms_member.phone %> </td>
      <td> <%= ms_member.email %> </td>
     <td class="text-center">
     		<%= link_to 'Delete',ms_member_path(ms_member), method: :delete, data: {confirm: 'Delete Data ? '}, class: 'btn btn-danger' %>
              <%= link_to 'Detail', ms_member_path(ms_member), class: 'btn btn-light' %>
              <%= link_to 'Edit', edit_ms_member_path(ms_member), class: 'btn btn-primary' %>
              
            </td>
      <% end %>
</tbody>
</tr>

app/views/ms_members/new.html.erb
  <div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_member) do |ms_member| %>

    	
        <div class="form-group">
          <%= ms_member.label :name %>
          <%= ms_member.text_field :name, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :Age %>
          <%= ms_member.text_field :age, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :address %>
          <%= ms_member.text_field :address, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :phone %>
          <%= ms_member.text_field :phone, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :email %>
          <%= ms_member.text_field :email, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <%= ms_member.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/ms_members/show.html.erb
<div class="container-fluid">
  <div class="row">
   <%= form_for(@ms_member) do |ms_member| %>
        
        <div class="form-group">
          <%= ms_member.label :name %>
          <%= ms_member.text_field :name, class:'form-control', type: 'text', placeholder: '', disabled: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :Age %>
          <%= ms_member.text_field :age, class:'form-control', type: 'number', placeholder: '', disabled: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :address %>
          <%= ms_member.text_field :address, class:'form-control', type: 'text', placeholder: '', disabled: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :phone %>
          <%= ms_member.text_field :phone, class:'form-control', type: 'number', placeholder: '', disabled: true %>
        </div>

        <div class="form-group">
          <%= ms_member.label :email %>
          <%= ms_member.text_field :email, class:'form-control', type: 'text', placeholder: '', disabled: true %>
        </div>

       <%= link_to 'Back', '/ms_members', class: 'btn btn-light' %>

    <% end %>
  </div>
</div>

app/views/ms_members/update.html.erb
<h1>MsMembers#update</h1>
<p>Find me in app/views/ms_members/update.html.erb</p>

app/views/ms_publishers/destroy.html.erb
<h1>MsPublishers#destroy</h1>
<p>Find me in app/views/ms_publishers/destroy.html.erb</p>

app/views/ms_publishers/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_publishers) do |ms_publisher| %>


        <div class="form-group">
          <%= ms_publisher.label :Name %>
          <%= ms_publisher.text_field :name, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_publisher.label :Phone %>
          <%= ms_publisher.text_field :phone, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= ms_publisher.label :Address %>
          <%= ms_publisher.text_field :address, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>



        <%= ms_publisher.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/ms_publishers/index.html.erb
<div style="float: right">
 <%= link_to 'Add Data', new_ms_publisher_path, class: 'btn btn-success' %>
 </div>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col" width="300px">Action</th>
    </tr>
  </thead>
<% @ms_publishers.each do |ms_publisher|%>
<tbody>
<tr>
      <th scope="row"><%= ms_publisher.id%></th>
      <td> <%= ms_publisher.name %> </td>
      <td> <%= ms_publisher.phone %> </td>
      <td> <%= ms_publisher.address %> </td>
     <td class="text-center">
     		<%= link_to 'Delete',ms_publisher_path(ms_publisher), method: :delete, data: {confirm: 'Delete Data ? '}, class: 'btn btn-danger' %>
              <%= link_to 'Detail', ms_publisher_path(ms_publisher), class: 'btn btn-light' %>
              <%= link_to 'Edit', edit_ms_publisher_path(ms_publisher), class: 'btn btn-primary' %>
              
            </td>
      <% end %>
</tbody>
</tr>

app/views/ms_publishers/new.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_publishers) do |ms_publisher| %>


        <div class="form-group">
          <%= ms_publisher.label :Name %>
          <%= ms_publisher.text_field :name, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>

        <div class="form-group">
          <%= ms_publisher.label :Phone %>
          <%= ms_publisher.text_field :phone, class:'form-control', type: 'number', placeholder: '',required: true %>
        </div>
        <div class="form-group">
          <%= ms_publisher.label :Address %>
          <%= ms_publisher.text_field :address, class:'form-control', type: 'text', placeholder: '',required: true %>
        </div>



        <%= ms_publisher.submit :Save, class:'btn btn-success' %>

    <% end %>
  </div>
</div>

app/views/ms_publishers/show.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_for(@ms_publishers) do |ms_publisher| %>


        <div class="form-group">
          <%= ms_publisher.label :Name %>
          <%= ms_publisher.text_field :name, class:'form-control', type: 'text', placeholder: '', disabled: true %>
        </div>

        <div class="form-group">
          <%= ms_publisher.label :Phone %>
          <%= ms_publisher.text_field :phone, class:'form-control', type: 'number', placeholder: '', disabled: true %>
        </div>
        <div class="form-group">
          <%= ms_publisher.label :Address %>
          <%= ms_publisher.text_field :address, class:'form-control', type: 'text', placeholder: '', disabled: true %>
        </div>



        <%= link_to 'Back', '/ms_publishers', class: 'btn btn-light' %>

    <% end %>
  </div>
</div>

app/views/ms_publishers/update.html.erb
<h1>MsPublishers#update</h1>
<p>Find me in app/views/ms_publishers/update.html.erb</p>

app/views/tr_loans/_edit.html.erb
<div class="modal-header text-center">
  <h4 class="modal-title w-100" id="myModalLabel">Borrow Book </h4>
</div>
<div class="modal-body">
<div class="form-group ">
	<%= label_tag(:name,"Member Name ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="name"></label>
	</div>
<div class="form-group ">
	<%= label_tag(:member_book,"Member Phone ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="phone"></label>
</div>
<div class="form-group ">
	<%= label_tag(:member_email,"Member Email ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label'id="email"></label>
</div>
<div class="form-group ">
	<%= label_tag(:book_id,"Book ID ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="book"></label>
</div>
<div class="form-group ">
	<%= label_tag(:borrow_date_id,"Borrow Date ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="borrow_date"></label>
</div>

	<%= form_for @tr_loans_form, method: :patch, scope: 'tr_loans' , html:{ id: 'tr_loans_form'} do |f| %>
	<%= f.hidden_field :status, value: 'Borrow' %>
	<div class="form-group ">
	<%= label_tag(:duration,"Duration ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<%= f.select(:duration, [['7 Days','7'], ['14 Days','14'],['21 Days','21']]) %>
	</div>
	<br>
	<br>
	<div class="text-center">
		<%= f.submit :save, class:'btn btn-success' %>
	</div>
	<% end %>
</div>
<script >


</script>

app/views/tr_loans/_edits.html.erb
<div class="modal-header text-center">
  <h4 class="modal-title w-100" id="myModalLabel">Return Book </h4>
</div>
<div class="modal-body">
<div class="form-group ">
	<%= label_tag(:name,"Member Name ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="name"></label>
	</div>
<div class="form-group ">
	<%= label_tag(:member_book,"Member Phone ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="phone"></label>
</div>
<div class="form-group ">
	<%= label_tag(:member_email,"Member Email ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label'id="email"></label>
</div>
<div class="form-group ">
	<%= label_tag(:book_id,"Book ID ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="book"></label>
</div>
<div class="form-group ">
	<%= label_tag(:borrow_date,"Borrow Date ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="borrow_date"></label>
</div>
<div class="form-group ">
	<%= label_tag(:borrow_date,"Return Date ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="return_date"></label>
</div>
<div class="form-group ">
	<%= label_tag(:duration,"Duration ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="duration"></label>
	</div>
<div class="form-group ">
	<%= label_tag(:bill,"Bill ",class:'col-sm-3 col-form-label') %>
	<label class="col-form-label">:</label>
	<label class= 'col-sm-2 col-form-label' id="bill"></label>
</div>

	<%= form_for @tr_loans_form, method: :patch, scope: 'tr_loans' , html:{ id: 'tr_loans_form'} do |f| %>
	<%= f.hidden_field :status, value: 'Return' %>
	<br>
	<br>
	<div class="text-center">
		<%= f.submit :save, class:'btn btn-success' %>
	</div>
	<% end %>
</div>
<script >


</script>

app/views/tr_loans/destroy.html.erb
<h1>TrLoans#destroy</h1>
<p>Find me in app/views/tr_loans/destroy.html.erb</p>

app/views/tr_loans/update.html.erb
<h1>TrLoans#update</h1>
<p>Find me in app/views/tr_loans/update.html.erb</p>